name: .NET Core

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:      
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    
    - name: Install Nerdbank.GitVersioning global tool
      uses: AArnott/nbgv@v0.3
    
    - name: Restore and Build
      run: dotnet build --configuration Debug
    
    - name: Test
      run: dotnet test --no-build --configuration Debug

    - name: Pack
      run: dotnet pack --no-build --configuration Debug -o ./packages

    - name: Upload packages as artifact
      uses: actions/upload-artifact@v1
      with:
        name: packages
        path: packages
