name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:      
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    
    - name: Restore and Build
      run: dotnet build --configuration Release
    
    - name: Start Redis
      uses: supercharge/redis-github-action@1.1.0
    
    - name: Test
      run: dotnet test --no-build --configuration Release --filter Category!=Windows

    - name: Pack
      run: dotnet pack --no-build --configuration Release -o ./packages

    - name: Upload packages as artifact
      uses: actions/upload-artifact@v1
      with:
        name: packages
        path: packages
        
    - name: Upload REstate bin
      uses: actions/upload-artifact@v1
      with:
        name: REstateBin
        path: ./src/REstate/bin/Release/netstandard2.0
